### ISSUE TITLE
api.helium.io generates 503 errors after first 100 challenges returned

### ISSUE THREAD

**Issue by synfinatic** [helium/blockchain-http#245]
Using [helium-analysis](https://github.com/synfinatic/helium-analysis) to pull challenges for a hotspot.

Can either pull `main` or the latest `v0.9.1` release:

init db: 
`./helium-analysis --init-db hotspots refresh`

pull challenges
```
./helium-analysis challenges refresh passive-umber-rat -L debug
DEBU[0000] Database challenges: 2021-03-12 17:13:28 UTC => 2021-04-08 04:21:47 UTC
INFO[0000] Last database record is before 2021-04-25 16:02:24 UTC
DEBU[0000] Loading challenges until: 2021-04-07 22:21:47 UTC
DEBU[0005] Helium API Cursor: eyJ0eXBlcyI6InBvY19yZWNlaXB0c192MSIsIm1pbl9ibG9jayI6MTc5NDI4LCJibG9jayI6ODE4OTAwLCJhbmNob3JfYmxvY2siOjgxODkwMH0
INFO[0076] Loaded 100 challenges
INFO[0076] Last challenge time: 2021-04-24 11:05:42 PDT
DEBU[0081] Helium API Cursor: eyJ0eXBlcyI6InBvY19yZWNlaXB0c192MSIsInR4biI6IlFqQ3E1WTRySlRBMzlHTzBmaHh2MEdfX3FjV0NWUGJtR19MTllZUXhUNzQiLCJtaW5fYmxvY2siOjE3OTQyOCwiYmxvY2siOjgxNzI0NSwiYW5jaG9yX2Jsb2NrIjo4MTg5MDB9
ERRO[0111] Error from server.  Backing off attempt 1 and trying again...
DEBU[0111] Error 503: {"error":"Too Busy"}
DEBU[0113] Helium API Cursor: eyJ0eXBlcyI6InBvY19yZWNlaXB0c192MSIsInR4biI6IlFqQ3E1WTRySlRBMzlHTzBmaHh2MEdfX3FjV0NWUGJtR19MTllZUXhUNzQiLCJtaW5fYmxvY2siOjE3OTQyOCwiYmxvY2siOjgxNzI0NSwiYW5jaG9yX2Jsb2NrIjo4MTg5MDB9
ERRO[0143] Error from server.  Backing off attempt 2 and trying again...
DEBU[0143] Error 503: {"error":"Too Busy"}
DEBU[0146] Helium API Cursor: eyJ0eXBlcyI6InBvY19yZWNlaXB0c192MSIsInR4biI6IlFqQ3E1WTRySlRBMzlHTzBmaHh2MEdfX3FjV0NWUGJtR19MTllZUXhUNzQiLCJtaW5fYmxvY2siOjE3OTQyOCwiYmxvY2siOjgxNzI0NSwiYW5jaG9yX2Jsb2NrIjo4MTg5MDB9
ERRO[0176] Error from server.  Backing off attempt 3 and trying again...
DEBU[0176] Error 503: {"error":"Too Busy"}
DEBU[0181] Helium API Cursor: eyJ0eXBlcyI6InBvY19yZWNlaXB0c192MSIsInR4biI6IlFqQ3E1WTRySlRBMzlHTzBmaHh2MEdfX3FjV0NWUGJtR19MTllZUXhUNzQiLCJtaW5fYmxvY2siOjE3OTQyOCwiYmxvY2siOjgxNzI0NSwiYW5jaG9yX2Jsb2NrIjo4MTg5MDB9
ERRO[0211] Error from server.  Backing off attempt 4 and trying again...
DEBU[0211] Error 503: {"error":"Too Busy"}
DEBU[0217] Helium API Cursor: eyJ0eXBlcyI6InBvY19yZWNlaXB0c192MSIsInR4biI6IlFqQ3E1WTRySlRBMzlHTzBmaHh2MEdfX3FjV0NWUGJtR19MTllZUXhUNzQiLCJtaW5fYmxvY2siOjE3OTQyOCwiYmxvY2siOjgxNzI0NSwiYW5jaG9yX2Jsb2NrIjo4MTg5MDB9
ERRO[0247] Error from server.  Backing off attempt 5 and trying again...
DEBU[0247] Error 503: {"error":"Too Busy"}
DEBU[0254] Helium API Cursor: eyJ0eXBlcyI6InBvY19yZWNlaXB0c192MSIsInR4biI6IlFqQ3E1WTRySlRBMzlHTzBmaHh2MEdfX3FjV0NWUGJtR19MTllZUXhUNzQiLCJtaW5fYmxvY2siOjE3OTQyOCwiYmxvY2siOjgxNzI0NSwiYW5jaG9yX2Jsb2NrIjo4MTg5MDB9
ERRO[0269] Error from server.  Backing off attempt 6 and trying again...
DEBU[0269] Error 503: <?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
 "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
  <head>
    <title>503 first byte timeout</title>
  </head>
  <body>
    <h1>Error 503 first byte timeout</h1>
    <p>first byte timeout</p>
    <h3>Guru Mediation:</h3>
    <p>Details: cache-sjc10039-SJC 1619388414 2211359384</p>
    <hr>
    <p>Varnish cache server</p>
  </body>
</html>
DEBU[0278] Helium API Cursor: eyJ0eXBlcyI6InBvY19yZWNlaXB0c192MSIsInR4biI6IlFqQ3E1WTRySlRBMzlHTzBmaHh2MEdfX3FjV0NWUGJtR19MTllZUXhUNzQiLCJtaW5fYmxvY2siOjE3OTQyOCwiYmxvY2siOjgxNzI0NSwiYW5jaG9yX2Jsb2NrIjo4MTg5MDB9
ERRO[0293] Error from server.  Backing off attempt 7 and trying again...
DEBU[0293] Error 503: <?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
 "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
  <head>
    <title>503 first byte timeout</title>
  </head>
  <body>
    <h1>Error 503 first byte timeout</h1>
    <p>first byte timeout</p>
    <h3>Guru Mediation:</h3>
    <p>Details: cache-sjc10039-SJC 1619388438 2211547196</p>
    <hr>
    <p>Varnish cache server</p>
  </body>
</html>
DEBU[0304] Helium API Cursor: eyJ0eXBlcyI6InBvY19yZWNlaXB0c192MSIsInR4biI6IlFqQ3E1WTRySlRBMzlHTzBmaHh2MEdfX3FjV0NWUGJtR19MTllZUXhUNzQiLCJtaW5fYmxvY2siOjE3OTQyOCwiYmxvY2siOjgxNzI0NSwiYW5jaG9yX2Jsb2NrIjo4MTg5MDB9
ERRO[0319] Error from server.  Backing off attempt 8 and trying again...
DEBU[0319] Error 503: <?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
 "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
  <head>
    <title>503 first byte timeout</title>
  </head>
  <body>
    <h1>Error 503 first byte timeout</h1>
    <p>first byte timeout</p>
    <h3>Guru Mediation:</h3>
    <p>Details: cache-sjc10039-SJC 1619388464 2211751996</p>
    <hr>
    <p>Varnish cache server</p>
  </body>
</html>
DEBU[0331] Helium API Cursor: eyJ0eXBlcyI6InBvY19yZWNlaXB0c192MSIsInR4biI6IlFqQ3E1WTRySlRBMzlHTzBmaHh2MEdfX3FjV0NWUGJtR19MTllZUXhUNzQiLCJtaW5fYmxvY2siOjE3OTQyOCwiYmxvY2siOjgxNzI0NSwiYW5jaG9yX2Jsb2NrIjo4MTg5MDB9
ERRO[0346] Error from server.  Backing off attempt 9 and trying again...
DEBU[0346] Error 503: <?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
 "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
  <head>
    <title>503 first byte timeout</title>
  </head>
  <body>
    <h1>Error 503 first byte timeout</h1>
    <p>first byte timeout</p>
    <h3>Guru Mediation:</h3>
    <p>Details: cache-sjc10039-SJC 1619388491 2211965144</p>
    <hr>
    <p>Varnish cache server</p>
  </body>
</html>
DEBU[0360] Helium API Cursor: eyJ0eXBlcyI6InBvY19yZWNlaXB0c192MSIsInR4biI6IlFqQ3E1WTRySlRBMzlHTzBmaHh2MEdfX3FjV0NWUGJtR19MTllZUXhUNzQiLCJtaW5fYmxvY2siOjE3OTQyOCwiYmxvY2siOjgxNzI0NSwiYW5jaG9yX2Jsb2NrIjo4MTg5MDB9
ERRO[0405] Error from server.  Backing off attempt 10 and trying again...
DEBU[0405] Error 503: {"error":"Too Busy"}
DEBU[0420] Helium API Cursor: eyJ0eXBlcyI6InBvY19yZWNlaXB0c192MSIsInR4biI6IlFqQ3E1WTRySlRBMzlHTzBmaHh2MEdfX3FjV0NWUGJtR19MTllZUXhUNzQiLCJtaW5fYmxvY2siOjE3OTQyOCwiYmxvY2siOjgxNzI0NSwiYW5jaG9yX2Jsb2NrIjo4MTg5MDB9
PANI[0435] Error running command: Unable to load challenges: Error 503: <?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
 "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
  <head>
    <title>503 first byte timeout</title>
  </head>
  <body>
    <h1>Error 503 first byte timeout</h1>
    <p>first byte timeout</p>
    <h3>Guru Mediation:</h3>
    <p>Details: cache-sjc10039-SJC 1619388580 2212665074</p>
    <hr>
    <p>Varnish cache server</p>
  </body>
</html>
panic: (*logrus.Entry) 0xc0000c2310

goroutine 1 [running]:
github.com/sirupsen/logrus.Entry.log(0xc0000c2000, 0xc00017e2d0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/aturner/go/pkg/mod/github.com/sirupsen/logrus@v1.7.0/entry.go:255 +0x325
github.com/sirupsen/logrus.(*Entry).Log(0xc0000c20e0, 0x0, 0xc000549e60, 0x1, 0x1)
	/Users/aturner/go/pkg/mod/github.com/sirupsen/logrus@v1.7.0/entry.go:283 +0xf0
github.com/sirupsen/logrus.(*Entry).Logf(0xc0000c20e0, 0xc000000000, 0x1501af1, 0x19, 0xc000549f38, 0x1, 0x1)
	/Users/aturner/go/pkg/mod/github.com/sirupsen/logrus@v1.7.0/entry.go:329 +0xe5
github.com/sirupsen/logrus.(*Logger).Logf(0xc0000c2000, 0x0, 0x1501af1, 0x19, 0xc000549f38, 0x1, 0x1)
	/Users/aturner/go/pkg/mod/github.com/sirupsen/logrus@v1.7.0/logger.go:151 +0x95
github.com/sirupsen/logrus.(*Logger).Panicf(...)
	/Users/aturner/go/pkg/mod/github.com/sirupsen/logrus@v1.7.0/logger.go:192
github.com/sirupsen/logrus.Panicf(...)
	/Users/aturner/go/pkg/mod/github.com/sirupsen/logrus@v1.7.0/exported.go:219
main.main()
	/Users/aturner/go/src/github.com/synfinatic/helium-analysis/cmd/main.go:96 +0x32c
```

**Comment by synfinatic** [comment]
FWIW, this issue is still happening today.  I've been completely unable to get past 100 records.

**Comment by nathan7432** [comment]
I have duplicated this error outside of helium analysis tools.

```
import requests

OON_address = '112UxrVuoSFUymU8HrqW8af9CoY5VkrJUfYDYuhnHiPsH7Lza9Lc'

active = requests.get(f'https://api.helium.io/v1/hotspots/{OON_address}/challenges')
active = active.json()

cursor1 = active.get('cursor')
active2 = requests.get(f'https://api.helium.io/v1/hotspots/{OON_address}/challenges/?cursor={cursor1}')
active2 = active2.json()

cursor2 = active2.get('cursor')
active3 = requests.get(f'https://api.helium.io/v1/hotspots/{OON_address}/challenges/?cursor={cursor2}') # Fails on this request
active3 = active3.json()
```

cursor1 = `eyJ0eXBlcyI6InBvY19yZWNlaXB0c192MSIsIm1pbl9ibG9jayI6NDU4Njg4LCJibG9jayI6ODI0NTAwLCJhbmNob3JfYmxvY2siOjgyNDUwMH0`
cursor2 = `eyJ0eXBlcyI6InBvY19yZWNlaXB0c192MSIsInR4biI6IjJpYUhoZ054VzNYMnEtZTVBenlNZjljNDdFT2ZEdTBoRWtjcUNTeGNmRkEiLCJtaW5fYmxvY2siOjQ1ODY4OCwiYmxvY2siOjgyMTA1MywiYW5jaG9yX2Jsb2NrIjo4MjQ1MDB9`
